---
- name: Configure firewall
  hosts: <target_hosts>
  tasks:

    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        service: https
        permanent: yes
        state: enabled

    - ansible.posix.firewalld: Enable ports
        port: 161-162/udp
        permanent: yes
        state: enabled

    - name: Redirect port 443 to 8443 with Rich Rule
      ansible.posix.firewalld:
        rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
